import mongoose from 'mongoose';
import Product from './models/productModel.js';
import dotenv from 'dotenv';

dotenv.config();

// Helper function to generate products for a category
const generateProducts = (category, count, baseData) => {
  const products = [];
  for (let i = 0; i < count; i++) {
    const productName = baseData.names[i % baseData.names.length];
    const isOutOfStock = Math.random() < 0.15; // 15% chance of being out of stock
    products.push({
      name: productName,
      slug: `${productName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${i + 1}`,
      color: baseData.colors[i % baseData.colors.length],
      category: category,
      image: baseData.images[i % baseData.images.length],
      price:
        baseData.priceRange[0] +
        Math.random() * (baseData.priceRange[1] - baseData.priceRange[0]),
      countInStock: isOutOfStock ? 0 : Math.floor(Math.random() * 50) + 5,
      brand: baseData.brands[i % baseData.brands.length],
      rating: (Math.random() * 2 + 3).toFixed(1),
      numReviews: Math.floor(Math.random() * 500) + 50,
      description: `${productName} - ${baseData.description}`,
    });
  }
  return products;
};

const categoryData = {
  Electronics: {
    count: 50,
    names: [
      'iPhone 15 Pro Max',
      'MacBook Pro 14"',
      'Samsung Galaxy S24 Ultra',
      'Sony WH-1000XM5 Headphones',
      'iPad Pro 12.9"',
      'Dell XPS 15 Laptop',
      'LG OLED TV 65"',
      'Microsoft Surface Pro 9',
      'Apple Watch Series 9',
      'Samsung Galaxy Watch 6',
      'Bose QuietComfort Earbuds',
      'JBL Flip 6 Speaker',
      'Nintendo Switch OLED',
      'PlayStation 5',
      'Xbox Series X',
      'Canon EOS R6 Camera',
      'GoPro Hero 12',
      'DJI Mini 3 Pro Drone',
      'Kindle Paperwhite',
      'Logitech MX Master 3S Mouse',
      'Samsung 49" Odyssey Monitor',
      'Apple AirPods Pro 2',
      'Anker PowerCore 26800',
      'Razer DeathAdder V3',
      'Western Digital 4TB SSD',
      'SanDisk Extreme Pro SD Card',
      'TP-Link Archer AX73 Router',
      'Netgear Orbi WiFi 6 System',
      'ASUS ROG Strix Gaming Laptop',
      'HP Spectre x360',
      'Lenovo ThinkPad X1 Carbon',
      'Google Pixel 8 Pro',
      'OnePlus 11 5G',
      'Motorola Edge 40',
      'Nothing Phone 2',
      'Sony Xperia 1 V',
      'Google Pixel Tablet',
      'Samsung Galaxy Tab S9',
      'Apple MacBook Air M3',
      'Microsoft Surface Laptop Studio 2',
      'Dell Alienware m18',
      'HP Omen 16 Gaming Laptop',
      'Lenovo Legion Pro 7i',
      'ASUS Zenbook Pro 14',
      'Samsung Galaxy Book3 Ultra',
      'LG Gram 17"',
      'Microsoft Surface Go 4',
    ],
    colors: ['Black', 'Silver', 'White', 'Blue', 'Red', 'Gray'],
    images: [
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500',
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500',
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500',
      'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=500',
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500',
      'https://images.unsplash.com/photo-1580910051074-3eb694886f9d?w=500',
    ],
    priceRange: [50, 2000],
    brands: [
      'Apple',
      'Samsung',
      'Sony',
      'LG',
      'Dell',
      'HP',
      'Microsoft',
      'Asus',
    ],
    description:
      'High-quality electronic device with advanced features and modern technology.',
  },
  Fashion: {
    count: 50,
    names: [
      'Classic Leather Jacket',
      'Slim Fit Chinos',
      'Designer Sunglasses',
      'Premium Cotton T-Shirt',
      'Running Sneakers',
      'Denim Jeans',
      'Casual Button-Up Shirt',
      'Wool Blend Sweater',
      'Polo Shirt',
      'Cargo Shorts',
      'Linen Pants',
      'Winter Parka Jacket',
      'Canvas Sneakers',
      'Leather Boots',
      'Dress Shoes',
      'Athletic Leggings',
      'Sports Bra',
      'Yoga Pants',
      'Hoodie',
      'Sweatpants',
      'Blazer',
      'Dress Shirt',
      'Pleated Trousers',
      'Cardigan',
      'Trench Coat',
      'Peacoat',
      'Vest',
      'Scarf',
      'Beanie',
      'Baseball Cap',
      'Leather Belt',
      'Canvas Belt',
      'Wristwatch',
      'Leather Wallet',
      'Backpack',
      'Messenger Bag',
      'Crossbody Bag',
      'Tote Bag',
      'Clutch',
      'Evening Bag',
      'Sunglasses Case',
      'Shoe Trees',
      'Tie',
      'Pocket Square',
      'Cufflinks',
      'Socks Pack',
      'Underwear Set',
      'Sleepwear Set',
      'Swim Trunks',
      'Bikini Set',
      'Cover-Up',
      'Beach Towel',
    ],
    colors: ['Black', 'White', 'Blue', 'Red', 'Green', 'Brown', 'Gray', 'Pink'],
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500',
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500',
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500',
      'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=500',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=500',
    ],
    priceRange: [20, 500],
    brands: [
      'Zara',
      'H&M',
      'Nike',
      'Adidas',
      "Levi's",
      'Gucci',
      'Prada',
      'Uniqlo',
    ],
    description:
      'Stylish fashion item with premium materials and contemporary design.',
  },
  Home: {
    count: 50,
    names: [
      'Modern Sofa Set',
      'Smart LED TV 55"',
      'Coffee Table',
      'Floor Lamp',
      'Bedding Set Queen',
      'Dining Table Set',
      'Recliner Chair',
      'Bookshelf',
      'Wardrobe',
      'Nightstand',
      'Area Rug',
      'Curtains Set',
      'Throw Pillows',
      'Wall Art',
      'Mirror',
      'Kitchen Island',
      'Bar Stools',
      'Dining Chairs',
      'Sideboard',
      'Console Table',
      'Desk Lamp',
      'Office Chair',
      'Standing Desk',
      'File Cabinet',
      'Shelving Unit',
      'Laundry Hamper',
      'Storage Bins',
      'Coat Rack',
      'Entryway Bench',
      'Shoe Rack',
      'Bathroom Vanity',
      'Shower Curtain',
      'Bath Towel Set',
      'Toilet Paper Holder',
      'Soap Dispenser',
      'Plant Pot',
      'Artificial Plant',
      'Vase',
      'Candle Set',
      'Diffuser',
      'Throw Blanket',
      'Cushion Set',
      'Ottoman',
      'Pouf',
      'Bean Bag Chair',
      'Ceiling Fan',
      'Air Purifier',
      'Humidifier',
      'Space Heater',
      'Electric Fireplace',
    ],
    colors: ['White', 'Brown', 'Gray', 'Black', 'Beige', 'Blue'],
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500',
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500',
      'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=500',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500',
    ],
    priceRange: [30, 1500],
    brands: [
      'IKEA',
      'West Elm',
      'Target',
      'Amazon Basics',
      'Philips',
      'Brooklinen',
    ],
    description: 'Quality home product designed for comfort and functionality.',
  },
  Beauty: {
    count: 50,
    names: [
      'Vitamin C Serum',
      'Hydrating Face Moisturizer',
      'Luxury Perfume',
      'Makeup Brush Set',
      'Hair Care Bundle',
      'Face Cleanser',
      'Toner',
      'Exfoliator',
      'Face Mask Set',
      'Eye Cream',
      'Lipstick Set',
      'Foundation',
      'Concealer',
      'Mascara',
      'Eyeliner',
      'Blush Palette',
      'Highlighter',
      'Setting Powder',
      'Primer',
      'Makeup Remover',
      'Shampoo',
      'Conditioner',
      'Hair Mask',
      'Hair Oil',
      'Styling Gel',
      'Body Lotion',
      'Body Wash',
      'Hand Cream',
      'Foot Cream',
      'Body Scrub',
      'Sunscreen SPF 50',
      'Self Tanner',
      'Bronzer',
      'Setting Spray',
      'Makeup Bag',
      'Nail Polish Set',
      'Manicure Kit',
      'Pedicure Kit',
      'Nail File',
      'Cuticle Oil',
      'Perfume Sample Set',
      'Cologne',
      'Body Spray',
      'Deodorant',
      'After Shave',
      'Razor Set',
      'Shaving Cream',
      'Beard Oil',
      'Hair Trimmer',
      'Electric Shaver',
    ],
    colors: ['White', 'Pink', 'Gold', 'Black', 'Red', 'Purple'],
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500',
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500',
      'https://images.unsplash.com/photo-1541643600914-78b084683601?w=500',
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=500',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500',
      'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=500',
    ],
    priceRange: [15, 300],
    brands: [
      'The Ordinary',
      'CeraVe',
      'Chanel',
      'Dior',
      'MAC',
      'Olaplex',
      "L'Oreal",
    ],
    description:
      'Premium beauty product for enhancing your natural beauty and skincare routine.',
  },
  Books: {
    count: 50,
    names: [
      'Bestselling Novel',
      'Self-Help Guide',
      'Cooking Masterclass',
      'Science Fiction Trilogy',
      'Art History Book',
      'Mystery Thriller',
      'Romance Novel',
      'Fantasy Series',
      'Biography',
      'History Book',
      'Science Textbook',
      'Math Workbook',
      'Language Learning Guide',
      'Travel Guide',
      "Children's Picture Book",
      'Young Adult Novel',
      'Graphic Novel',
      'Comic Book Collection',
      'Poetry Anthology',
      'Short Story Collection',
      'Business Book',
      'Finance Guide',
      'Marketing Handbook',
      'Leadership Book',
      'Productivity Guide',
      'Philosophy Book',
      'Psychology Textbook',
      'Sociology Study',
      'Political Science',
      'Economics Primer',
      'Art Book',
      'Photography Collection',
      'Design Manual',
      'Architecture Guide',
      'Fashion Book',
      'Music Theory',
      'Instrument Guide',
      'Songwriting Book',
      'Music History',
      'Biography of Musician',
      'Health Guide',
      'Fitness Book',
      'Nutrition Guide',
      'Wellness Book',
      'Mental Health Guide',
      'Gardening Book',
      'DIY Manual',
      'Craft Guide',
      'Hobby Book',
      'Pet Care Guide',
    ],
    colors: ['Blue', 'Red', 'Green', 'Black', 'Brown', 'Yellow'],
    images: [
      'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500',
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500',
      'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=500',
      'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=500',
      'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=500',
    ],
    priceRange: [10, 100],
    brands: [
      'Penguin',
      'HarperCollins',
      'Random House',
      'Simon & Schuster',
      'Macmillan',
      'Tor Books',
    ],
    description:
      'Engaging book that captivates readers with compelling stories and valuable insights.',
  },
  Sports: {
    count: 50,
    names: [
      'Professional Basketball',
      'Yoga Mat Premium',
      'Adjustable Dumbbells Set',
      'Running Watch GPS',
      'Tennis Racket Pro',
      'Soccer Ball',
      'Football',
      'Baseball Glove',
      'Hockey Stick',
      'Golf Club Set',
      'Swimming Goggles',
      'Water Bottle',
      'Sports Towel',
      'Gym Bag',
      'Resistance Bands Set',
      'Jump Rope',
      'Boxing Gloves',
      'Punching Bag',
      'Speed Bag',
      'MMA Gloves',
      'Cycling Helmet',
      'Bike Lights',
      'Bike Lock',
      'Cycling Shorts',
      'Cycling Jersey',
      'Hiking Boots',
      'Trekking Poles',
      'Camping Tent',
      'Sleeping Bag',
      'Camping Stove',
      'Fishing Rod',
      'Tackle Box',
      'Kayak Paddle',
      'Life Jacket',
      'Snorkel Set',
      'Skateboard',
      'Roller Skates',
      'Protective Pads',
      'Helmet',
      'Elbow Pads',
      'Tennis Balls',
      'Badminton Racket',
      'Table Tennis Paddle',
      'Volleyball',
      'Squash Racket',
      'Gym Gloves',
      'Weightlifting Belt',
      'Knee Sleeves',
      'Wrist Wraps',
      'Lifting Straps',
    ],
    colors: ['Black', 'Red', 'Blue', 'Green', 'Orange', 'White'],
    images: [
      'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=500',
      'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500',
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=500',
      'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=500',
      'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500',
    ],
    priceRange: [20, 500],
    brands: [
      'Nike',
      'Adidas',
      'Under Armour',
      'Wilson',
      'Spalding',
      'Garmin',
      'Bowflex',
    ],
    description:
      'Professional sports equipment designed for performance and durability.',
  },
  Toys: {
    count: 50,
    names: [
      'LEGO Creative Set',
      'Remote Control Car',
      'Board Game Collection',
      'Art Supplies Kit',
      'STEM Building Kit',
      'Doll House',
      'Action Figure Set',
      'Puzzle Collection',
      'Play-Doh Set',
      'Kinetic Sand',
      'Stuffed Animal',
      'Plush Toy',
      'Ride-On Car',
      'Tricycle',
      'Scooter',
      'Science Kit',
      'Chemistry Set',
      'Microscope Set',
      'Telescope',
      'Binoculars',
      'Musical Instrument Set',
      'Keyboard',
      'Drum Set',
      'Guitar for Kids',
      'Recorder',
      'Outdoor Play Set',
      'Swing Set',
      'Slide',
      'Sand Box',
      'Playhouse',
      'Water Gun Set',
      'Pool Floats',
      'Beach Toys',
      'Bubble Machine',
      'Kite',
      'Train Set',
      'Race Track Set',
      'Car Collection',
      'Airplane Model',
      'Ship Model',
      'Costume Set',
      'Dress-Up Clothes',
      'Accessories Set',
      'Face Paint Kit',
      'Magic Set',
      'Craft Kit',
      'Jewelry Making Kit',
      'Sewing Kit',
      'Knitting Set',
      'Origami Set',
    ],
    colors: ['Multicolor', 'Blue', 'Red', 'Green', 'Yellow', 'Pink'],
    images: [
      'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500',
      'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=500',
      'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=500',
      'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=500',
      'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=500',
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=500',
    ],
    priceRange: [15, 200],
    brands: [
      'LEGO',
      'Hasbro',
      'Mattel',
      'Fisher-Price',
      'Crayola',
      "K'NEX",
      'Traxxas',
    ],
    description:
      'Fun and educational toy designed to inspire creativity and learning.',
  },
  Groceries: {
    count: 50,
    names: [
      'Organic Coffee Beans',
      'Extra Virgin Olive Oil',
      'Artisan Pasta Set',
      'Premium Tea Collection',
      'Organic Honey',
      'Whole Grain Bread',
      'Fresh Eggs',
      'Organic Milk',
      'Greek Yogurt',
      'Cheese Variety Pack',
      'Fresh Fruits Basket',
      'Vegetable Box',
      'Organic Salad Mix',
      'Avocados',
      'Berries Pack',
      'Lean Chicken Breast',
      'Ground Beef',
      'Salmon Fillet',
      'Shrimp',
      'Tuna Steak',
      'Brown Rice',
      'Quinoa',
      'Oats',
      'Granola',
      'Cereal',
      'Peanut Butter',
      'Almond Butter',
      'Jam Collection',
      'Honey',
      'Maple Syrup',
      'Olive Oil',
      'Coconut Oil',
      'Avocado Oil',
      'Vinegar Set',
      'Spices Collection',
      'Pasta Sauce',
      'Canned Tomatoes',
      'Beans Variety',
      'Lentils',
      'Chickpeas',
      'Snack Pack',
      'Nuts Mix',
      'Dried Fruits',
      'Energy Bars',
      'Protein Bars',
      'Chocolate Collection',
      'Cookies Pack',
      'Crackers',
      'Chips Variety',
      'Popcorn',
    ],
    colors: ['Brown', 'Green', 'Yellow', 'Red', 'White', 'Golden'],
    images: [
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500',
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500',
      'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=500',
      'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500',
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500',
      'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500',
    ],
    priceRange: [5, 100],
    brands: [
      'Starbucks',
      'Colavita',
      'De Cecco',
      'Twinings',
      "Nature Nate's",
      'Organic Valley',
    ],
    description:
      'Quality grocery item sourced from trusted suppliers for your daily needs.',
  },
};

// Generate all products
const products = [];
Object.keys(categoryData).forEach((category) => {
  const data = categoryData[category];
  const categoryProducts = generateProducts(category, data.count, data);
  products.push(...categoryProducts);
});

const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing products
    await Product.deleteMany({});
    console.log('Cleared existing products');

    // Insert new products
    await Product.insertMany(products);
    console.log('Products seeded successfully');

    // Count products per category
    const categoryCounts = {};
    for (const category of Object.keys(categoryData)) {
      const count = await Product.countDocuments({ category });
      categoryCounts[category] = count;
    }

    console.log('\nCategory Product Counts:');
    Object.keys(categoryCounts).forEach((category) => {
      console.log(`${category}: ${categoryCounts[category]} products`);
    });

    console.log(`\nTotal products seeded: ${products.length}`);
    process.exit();
  } catch (error) {
    console.error('Error seeding products:', error);
    process.exit(1);
  }
};

seedProducts();
