import mongoose from 'mongoose';
import Product from './models/productModel.js';
import dotenv from 'dotenv';

dotenv.config();

const products = [
  // Electronics
  {
    name: 'iPhone 15 Pro Max',
    slug: 'iphone-15-pro-max',
    color: 'Titanium Blue',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500',
    price: 1199.99,
    countInStock: 50,
    brand: 'Apple',
    rating: 4.8,
    numReviews: 245,
    description: 'Latest iPhone with A17 Pro chip, 48MP camera system, and titanium design.',
  },
  {
    name: 'MacBook Pro 14"',
    slug: 'macbook-pro-14',
    color: 'Space Gray',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500',
    price: 1999.99,
    countInStock: 30,
    brand: 'Apple',
    rating: 4.9,
    numReviews: 189,
    description: 'Powerful laptop with M3 Pro chip, Liquid Retina XDR display, and all-day battery life.',
  },
  {
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    color: 'Phantom Black',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500',
    price: 1299.99,
    countInStock: 45,
    brand: 'Samsung',
    rating: 4.7,
    numReviews: 156,
    description: 'Premium Android smartphone with S Pen, 200MP camera, and AI features.',
  },
  {
    name: 'Sony WH-1000XM5 Headphones',
    slug: 'sony-wh-1000xm5',
    color: 'Black',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
    price: 349.99,
    countInStock: 75,
    brand: 'Sony',
    rating: 4.8,
    numReviews: 312,
    description: 'Industry-leading noise canceling headphones with exceptional sound quality.',
  },
  {
    name: 'iPad Pro 12.9"',
    slug: 'ipad-pro-12-9',
    color: 'Silver',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500',
    price: 1099.99,
    countInStock: 40,
    brand: 'Apple',
    rating: 4.7,
    numReviews: 198,
    description: 'Ultimate iPad experience with M2 chip and Liquid Retina XDR display.',
  },

  // Fashion
  {
    name: 'Classic Leather Jacket',
    slug: 'classic-leather-jacket',
    color: 'Brown',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
    price: 299.99,
    countInStock: 25,
    brand: 'Levi\'s',
    rating: 4.6,
    numReviews: 87,
    description: 'Timeless leather jacket with premium quality and modern fit.',
  },
  {
    name: 'Slim Fit Chinos',
    slug: 'slim-fit-chinos',
    color: 'Navy',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500',
    price: 79.99,
    countInStock: 100,
    brand: 'H&M',
    rating: 4.4,
    numReviews: 234,
    description: 'Versatile slim-fit chinos perfect for casual and formal occasions.',
  },
  {
    name: 'Designer Sunglasses',
    slug: 'designer-sunglasses',
    color: 'Black',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500',
    price: 189.99,
    countInStock: 60,
    brand: 'Ray-Ban',
    rating: 4.7,
    numReviews: 156,
    description: 'Iconic aviator sunglasses with UV protection and polarized lenses.',
  },
  {
    name: 'Premium Cotton T-Shirt',
    slug: 'premium-cotton-tshirt',
    color: 'White',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
    price: 39.99,
    countInStock: 200,
    brand: 'Uniqlo',
    rating: 4.5,
    numReviews: 445,
    description: 'High-quality cotton t-shirt with comfortable fit and durability.',
  },
  {
    name: 'Running Sneakers',
    slug: 'running-sneakers',
    color: 'Red',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
    price: 129.99,
    countInStock: 80,
    brand: 'Nike',
    rating: 4.8,
    numReviews: 312,
    description: 'Lightweight running shoes with responsive cushioning and breathable mesh.',
  },

  // Home & Living
  {
    name: 'Modern Sofa Set',
    slug: 'modern-sofa-set',
    color: 'Gray',
    category: 'Home',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500',
    price: 899.99,
    countInStock: 15,
    brand: 'IKEA',
    rating: 4.6,
    numReviews: 67,
    description: 'Contemporary 3-seater sofa with premium fabric and comfortable cushioning.',
  },
  {
    name: 'Smart LED TV 55"',
    slug: 'smart-led-tv-55',
    color: 'Black',
    category: 'Home',
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500',
    price: 699.99,
    countInStock: 35,
    brand: 'Samsung',
    rating: 4.7,
    numReviews: 189,
    description: '4K Smart TV with HDR, built-in streaming apps, and voice control.',
  },
  {
    name: 'Coffee Table',
    slug: 'coffee-table',
    color: 'Oak',
    category: 'Home',
    image: 'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=500',
    price: 249.99,
    countInStock: 45,
    brand: 'West Elm',
    rating: 4.5,
    numReviews: 98,
    description: 'Elegant solid wood coffee table with storage shelf and modern design.',
  },
  {
    name: 'Floor Lamp',
    slug: 'floor-lamp',
    color: 'Brass',
    category: 'Home',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500',
    price: 129.99,
    countInStock: 60,
    brand: 'Philips',
    rating: 4.4,
    numReviews: 76,
    description: 'Adjustable floor lamp with warm LED lighting and minimalist design.',
  },
  {
    name: 'Bedding Set Queen',
    slug: 'bedding-set-queen',
    color: 'White',
    category: 'Home',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500',
    price: 149.99,
    countInStock: 80,
    brand: 'Brooklinen',
    rating: 4.8,
    numReviews: 234,
    description: 'Luxury 400-thread count cotton bedding set with duvet cover and pillowcases.',
  },

  // Beauty
  {
    name: 'Vitamin C Serum',
    slug: 'vitamin-c-serum',
    color: 'Orange',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500',
    price: 49.99,
    countInStock: 150,
    brand: 'The Ordinary',
    rating: 4.7,
    numReviews: 567,
    description: 'Powerful antioxidant serum that brightens skin and reduces fine lines.',
  },
  {
    name: 'Hydrating Face Moisturizer',
    slug: 'hydrating-face-moisturizer',
    color: 'White',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500',
    price: 39.99,
    countInStock: 120,
    brand: 'CeraVe',
    rating: 4.6,
    numReviews: 445,
    description: 'Daily moisturizer with hyaluronic acid for all-day hydration.',
  },
  {
    name: 'Luxury Perfume',
    slug: 'luxury-perfume',
    color: 'Gold',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=500',
    price: 129.99,
    countInStock: 50,
    brand: 'Chanel',
    rating: 4.9,
    numReviews: 234,
    description: 'Elegant long-lasting fragrance with notes of jasmine and rose.',
  },
  {
    name: 'Makeup Brush Set',
    slug: 'makeup-brush-set',
    color: 'Black',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=500',
    price: 59.99,
    countInStock: 90,
    brand: 'Real Techniques',
    rating: 4.5,
    numReviews: 312,
    description: 'Professional 12-piece makeup brush set for flawless application.',
  },
  {
    name: 'Hair Care Bundle',
    slug: 'hair-care-bundle',
    color: 'Purple',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500',
    price: 79.99,
    countInStock: 70,
    brand: 'Olaplex',
    rating: 4.8,
    numReviews: 189,
    description: 'Complete hair repair system with shampoo, conditioner, and treatment.',
  },

  // Books
  {
    name: 'Bestselling Novel',
    slug: 'bestselling-novel',
    color: 'Blue',
    category: 'Books',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500',
    price: 24.99,
    countInStock: 200,
    brand: 'Penguin',
    rating: 4.7,
    numReviews: 567,
    description: 'Gripping thriller that will keep you on the edge of your seat.',
  },
  {
    name: 'Self-Help Guide',
    slug: 'self-help-guide',
    color: 'Green',
    category: 'Books',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500',
    price: 19.99,
    countInStock: 150,
    brand: 'HarperCollins',
    rating: 4.6,
    numReviews: 345,
    description: 'Transform your life with practical advice and actionable strategies.',
  },
  {
    name: 'Cooking Masterclass',
    slug: 'cooking-masterclass',
    color: 'Red',
    category: 'Books',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500',
    price: 34.99,
    countInStock: 100,
    brand: 'Williams Sonoma',
    rating: 4.8,
    numReviews: 234,
    description: 'Comprehensive cookbook with 100+ recipes from world-renowned chefs.',
  },
  {
    name: 'Science Fiction Trilogy',
    slug: 'science-fiction-trilogy',
    color: 'Silver',
    category: 'Books',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500',
    price: 44.99,
    countInStock: 80,
    brand: 'Tor Books',
    rating: 4.9,
    numReviews: 456,
    description: 'Epic space opera spanning galaxies and generations.',
  },
  {
    name: 'Art History Book',
    slug: 'art-history-book',
    color: 'Gold',
    category: 'Books',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500',
    price: 59.99,
    countInStock: 60,
    brand: 'Taschen',
    rating: 4.7,
    numReviews: 123,
    description: 'Beautifully illustrated journey through art history masterpieces.',
  },

  // Sports
  {
    name: 'Professional Basketball',
    slug: 'professional-basketball',
    color: 'Orange',
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=500',
    price: 49.99,
    countInStock: 100,
    brand: 'Spalding',
    rating: 4.6,
    numReviews: 234,
    description: 'Official size and weight basketball for indoor and outdoor play.',
  },
  {
    name: 'Yoga Mat Premium',
    slug: 'yoga-mat-premium',
    color: 'Purple',
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500',
    price: 39.99,
    countInStock: 150,
    brand: 'Manduka',
    rating: 4.7,
    numReviews: 345,
    description: 'Extra-thick yoga mat with non-slip surface and carrying strap.',
  },
  {
    name: 'Adjustable Dumbbells Set',
    slug: 'adjustable-dumbbells-set',
    color: 'Black',
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500',
    price: 299.99,
    countInStock: 40,
    brand: 'Bowflex',
    rating: 4.8,
    numReviews: 189,
    description: 'Space-saving adjustable dumbbells with weight range 5-52.5 lbs.',
  },
  {
    name: 'Running Watch GPS',
    slug: 'running-watch-gps',
    color: 'Black',
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=500',
    price: 199.99,
    countInStock: 70,
    brand: 'Garmin',
    rating: 4.7,
    numReviews: 267,
    description: 'Advanced GPS running watch with heart rate monitor and training features.',
  },
  {
    name: 'Tennis Racket Pro',
    slug: 'tennis-racket-pro',
    color: 'Red',
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=500',
    price: 179.99,
    countInStock: 55,
    brand: 'Wilson',
    rating: 4.6,
    numReviews: 145,
    description: 'Professional-grade tennis racket with optimal balance and power.',
  },

  // Toys
  {
    name: 'LEGO Creative Set',
    slug: 'lego-creative-set',
    color: 'Multicolor',
    category: 'Toys',
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500',
    price: 59.99,
    countInStock: 80,
    brand: 'LEGO',
    rating: 4.9,
    numReviews: 567,
    description: '1000+ piece LEGO set for creative building and endless fun.',
  },
  {
    name: 'Remote Control Car',
    slug: 'remote-control-car',
    color: 'Blue',
    category: 'Toys',
    image: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=500',
    price: 79.99,
    countInStock: 60,
    brand: 'Traxxas',
    rating: 4.5,
    numReviews: 234,
    description: 'High-speed RC car with rechargeable battery and off-road capabilities.',
  },
  {
    name: 'Board Game Collection',
    slug: 'board-game-collection',
    color: 'Various',
    category: 'Toys',
    image: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=500',
    price: 49.99,
    countInStock: 90,
    brand: 'Hasbro',
    rating: 4.7,
    numReviews: 345,
    description: 'Collection of classic board games for family game nights.',
  },
  {
    name: 'Art Supplies Kit',
    slug: 'art-supplies-kit',
    color: 'Rainbow',
    category: 'Toys',
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=500',
    price: 34.99,
    countInStock: 120,
    brand: 'Crayola',
    rating: 4.6,
    numReviews: 189,
    description: 'Complete art kit with markers, crayons, colored pencils, and paper.',
  },
  {
    name: 'STEM Building Kit',
    slug: 'stem-building-kit',
    color: 'Orange',
    category: 'Toys',
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500',
    price: 69.99,
    countInStock: 70,
    brand: 'K\'NEX',
    rating: 4.8,
    numReviews: 267,
    description: 'Educational building kit that teaches engineering and problem-solving skills.',
  },

  // Groceries
  {
    name: 'Organic Coffee Beans',
    slug: 'organic-coffee-beans',
    color: 'Brown',
    category: 'Groceries',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500',
    price: 24.99,
    countInStock: 200,
    brand: 'Starbucks',
    rating: 4.7,
    numReviews: 567,
    description: 'Premium Arabica coffee beans, ethically sourced and freshly roasted.',
  },
  {
    name: 'Extra Virgin Olive Oil',
    slug: 'extra-virgin-olive-oil',
    color: 'Green',
    category: 'Groceries',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500',
    price: 29.99,
    countInStock: 150,
    brand: 'Colavita',
    rating: 4.6,
    numReviews: 345,
    description: 'Cold-pressed extra virgin olive oil from Italy, perfect for cooking and dressings.',
  },
  {
    name: 'Artisan Pasta Set',
    slug: 'artisan-pasta-set',
    color: 'Yellow',
    category: 'Groceries',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=500',
    price: 19.99,
    countInStock: 180,
    brand: 'De Cecco',
    rating: 4.8,
    numReviews: 234,
    description: 'Variety pack of authentic Italian pasta shapes made from durum wheat.',
  },
  {
    name: 'Premium Tea Collection',
    slug: 'premium-tea-collection',
    color: 'Green',
    category: 'Groceries',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500',
    price: 34.99,
    countInStock: 120,
    brand: 'Twinings',
    rating: 4.7,
    numReviews: 189,
    description: 'Assortment of premium black, green, and herbal teas in elegant tins.',
  },
  {
    name: 'Organic Honey',
    slug: 'organic-honey',
    color: 'Golden',
    category: 'Groceries',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500',
    price: 18.99,
    countInStock: 160,
    brand: 'Nature Nate\'s',
    rating: 4.5,
    numReviews: 267,
    description: 'Pure, raw organic honey from local beekeepers, unfiltered and unpasteurized.',
  },
];

const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing products
    await Product.deleteMany({});
    console.log('Cleared existing products');

    // Insert new products
    await Product.insertMany(products);
    console.log('Products seeded successfully');

    console.log(`Total products seeded: ${products.length}`);
    process.exit();
  } catch (error) {
    console.error('Error seeding products:', error);
    process.exit(1);
  }
};

seedProducts();
