import mongoose from 'mongoose';
import Product from './models/productModel.js';
import dotenv from 'dotenv';

dotenv.config();

const categoryData = {
  Electronics: {
    count: 50,
    names: [
      'iPhone 15 Pro Max',
      'MacBook Pro 14"',
      'Samsung Galaxy S24 Ultra',
      'Sony WH-1000XM5 Headphones',
      'iPad Pro 12.9"',
      'Dell XPS 15 Laptop',
      'LG OLED TV 65"',
      'Microsoft Surface Pro 9',
      'Apple Watch Series 9',
      'Samsung Galaxy Watch 6',
      'Bose QuietComfort Earbuds',
      'JBL Flip 6 Speaker',
      'Nintendo Switch OLED',
      'PlayStation 5',
      'Xbox Series X',
      'Canon EOS R6 Camera',
      'GoPro Hero 12',
      'DJI Mini 3 Pro Drone',
      'Kindle Paperwhite',
      'Logitech MX Master 3S Mouse',
      'Samsung 49" Odyssey Monitor',
      'Apple AirPods Pro 2',
      'Anker PowerCore 26800',
      'Razer DeathAdder V3',
      'Western Digital 4TB SSD',
      'SanDisk Extreme Pro SD Card',
      'TP-Link Archer AX73 Router',
      'Netgear Orbi WiFi 6 System',
      'ASUS ROG Strix Gaming Laptop',
      'HP Spectre x360',
      'Lenovo ThinkPad X1 Carbon',
      'Google Pixel 8 Pro',
      'OnePlus 11 5G',
      'Motorola Edge 40',
      'Nothing Phone 2',
      'Sony Xperia 1 V',
      'Google Pixel Tablet',
      'Samsung Galaxy Tab S9',
      'Apple MacBook Air M3',
      'Microsoft Surface Laptop Studio 2',
      'Dell Alienware m18',
      'HP Omen 16 Gaming Laptop',
      'Lenovo Legion Pro 7i',
      'ASUS Zenbook Pro 14',
      'Samsung Galaxy Book3 Ultra',
      'LG Gram 17"',
      'Microsoft Surface Go 4',
    ],
    colors: ['Black', 'Silver', 'White', 'Blue', 'Red', 'Gray'],
    images: [
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500',
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500',
      'https://images.unsplash.com/photo-1610945415295-d9bbf69173e03?w=500',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500',
      'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=500',
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500',
      'https://images.unsplash.com/photo-1580910051074-3eb694886f9d?w=500',
    ],
    priceRange: [50, 2000],
    brands: [
      'Apple',
      'Samsung',
      'Sony',
      'LG',
      'Dell',
      'HP',
      'Microsoft',
      'Asus',
    ],
    description:
      'High-quality electronic device with advanced features and modern technology.',
  },
  Fashion: {
    count: 50,
    names: [
      'Classic Leather Jacket',
      'Slim Fit Chinos',
      'Designer Sunglasses',
      'Premium Cotton T-Shirt',
      'Running Sneakers',
      'Denim Jeans',
      'Casual Button-Up Shirt',
      'Wool Blend Sweater',
      'Polo Shirt',
      'Cargo Shorts',
      'Linen Pants',
      'Winter Parka Jacket',
      'Canvas Sneakers',
      'Leather Boots',
      'Dress Shoes',
      'Athletic Leggings',
      'Sports Bra',
      'Yoga Pants',
      'Hoodie',
      'Cardigan',
      'Blazer',
      'Pleated Skirt',
      'Maxi Dress',
      'Midi Dress',
      'Mini Skirt',
      'Tank Top',
      'Crop Top',
      'Jumpsuit',
      'Romper',
      'Overalls',
      'Scarf',
      'Gloves',
      'Hat',
      'Belt',
      'Socks',
      'Underwear',
      'Swimsuit',
      'Cover-Up',
      'Beach Dress',
      'Sandals',
      'Flip Flops',
      'Loafers',
      'Oxford Shoes',
      'High Heels',
      'Flats',
      'Wedges',
      'Espadrilles',
      'Mules',
      'Slippers',
      'Pajamas',
      'Robe',
      'Nightgown',
    ],
    colors: ['Black', 'White', 'Blue', 'Red', 'Gray', 'Brown', 'Green'],
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
      'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=500',
      'https://images.unsplash.com/photo-1445205170230-053b83016050?w=500',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=500',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500',
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500',
      'https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=500',
    ],
    priceRange: [20, 300],
    brands: [
      'Nike',
      'Adidas',
      "Levi's",
      'Zara',
      'H&M',
      'Gucci',
      'Prada',
      'Ralph Lauren',
    ],
    description:
      'Stylish fashion item with premium materials and contemporary design.',
  },
  Home: {
    count: 50,
    names: [
      'Modern Sofa Set',
      'Coffee Table',
      'TV Stand',
      'Bookshelf',
      'Wardrobe',
      'Nightstand',
      'Area Rug',
      'Curtains Set',
      'Throw Pillows',
      'Wall Art',
      'Mirror',
      'Kitchen Island',
      'Bar Stools',
      'Dining Chairs',
      'Sideboard',
      'Console Table',
      'Desk Lamp',
      'Office Chair',
      'Standing Desk',
      'File Cabinet',
      'Shelving Unit',
      'Laundry Hamper',
      'Storage Bins',
      'Coat Rack',
      'Entryway Bench',
      'Shoe Rack',
      'Bathroom Vanity',
      'Shower Curtain',
      'Bath Towel Set',
      'Toilet Paper Holder',
      'Soap Dispenser',
      'Plant Pot',
      'Artificial Plant',
      'Vase',
      'Candle Set',
      'Diffuser',
      'Throw Blanket',
      'Cushion Set',
      'Ottoman',
      'Pouf',
      'Bean Bag Chair',
      'Ceiling Fan',
      'Air Purifier',
      'Humidifier',
      'Space Heater',
      'Electric Fireplace',
      'Bed Frame',
      'Mattress',
      'Pillows',
      'Comforter Set',
      'Duvet Cover',
      'Sheet Set',
    ],
    colors: ['White', 'Brown', 'Gray', 'Black', 'Beige', 'Blue'],
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500',
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500',
      'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=500',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500',
      'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=500',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500',
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=500',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500',
    ],
    priceRange: [30, 1500],
    brands: [
      'IKEA',
      'West Elm',
      'Pottery Barn',
      'Ashley Furniture',
      'Wayfair',
      'Target',
      'Walmart',
      'Amazon Basics',
    ],
    description: 'Quality home product designed for comfort and functionality.',
  },
  Beauty: {
    count: 50,
    names: [
      'Vitamin C Serum',
      'Moisturizing Cream',
      'Face Wash',
      'Toner',
      'Sunscreen SPF 50',
      'Night Cream',
      'Eye Cream',
      'Lip Balm',
      'Foundation',
      'Concealer',
      'Mascara',
      'Eyeliner',
      'Lipstick',
      'Blush',
      'Bronzer',
      'Highlighter',
      'Setting Powder',
      'Primer',
      'Makeup Remover',
      'Cleansing Oil',
      'Face Mask',
      'Sheet Mask',
      'Exfoliator',
      'Face Scrub',
      'Hair Shampoo',
      'Conditioner',
      'Hair Mask',
      'Hair Oil',
      'Hair Serum',
      'Hair Spray',
      'Styling Gel',
      'Heat Protectant',
      'Perfume',
      'Body Lotion',
      'Body Wash',
      'Body Scrub',
      'Hand Cream',
      'Foot Cream',
      'Nail Polish',
      'Nail Polish Remover',
      'Makeup Brushes',
      'Beauty Blender',
      'Cotton Pads',
      'Cotton Swabs',
      'Face Roller',
      'Jade Roller',
      'Gua Sha Tool',
      'Face Steamer',
      'Hair Dryer',
      'Curling Iron',
      'Straightener',
      'Hair Trimmer',
      'Electric Toothbrush',
      'Water Flosser',
      'Face Cleansing Brush',
      'Light Therapy Mask',
    ],
    colors: ['White', 'Pink', 'Gold', 'Black', 'Clear', 'Red'],
    images: [
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=500',
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=500',
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500',
      'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=500',
      'https://images.unsplash.com/photo-1570194065650-d99fb4b38b15?w=500',
      'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500',
      'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=500',
      'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500',
    ],
    priceRange: [10, 200],
    brands: [
      'Neutrogena',
      'Olay',
      "L'Oreal",
      'Maybelline',
      'MAC',
      'Estee Lauder',
      'Clinique',
      'Dior',
    ],
    description:
      'Premium beauty product for enhancing your natural beauty and skincare routine.',
  },
  Books: {
    count: 50,
    names: [
      'Bestselling Novel',
      'Self-Help Guide',
      'Cooking Book',
      'Science Fiction',
      'Mystery Thriller',
      'Romance Novel',
      'Biography',
      'History Book',
      'Business Book',
      'Psychology Guide',
      'Philosophy Book',
      'Art Book',
      'Travel Guide',
      "Children's Book",
      'Educational Textbook',
      'Language Learning',
      'Poetry Collection',
      'Short Stories',
      'Graphic Novel',
      'Comic Book',
      'Fantasy Series',
      'Adventure Novel',
      'Crime Fiction',
      'Horror Book',
      'Science Book',
      'Technology Guide',
      'Health & Fitness',
      'Parenting Guide',
      'Religious Text',
      'Spirituality Book',
      'Motivational Book',
      'Journal',
      'Planner',
      'Coloring Book',
      'Puzzle Book',
      'Activity Book',
      'Reference Book',
      'Dictionary',
      'Encyclopedia',
      'Atlas',
      'Magazine Subscription',
      'Newspaper',
      'Comic Strip Collection',
      'Art Prints',
      'Book Light',
      'Bookmark',
      'Book Stand',
      'Reading Pillow',
      'E-Reader Case',
      'Book Cover',
      'Bookend',
      'Bookshelf Organizer',
    ],
    colors: ['Blue', 'Red', 'Green', 'Yellow', 'Black', 'White'],
    images: [
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500',
      'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500',
      'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=500',
      'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=500',
      'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=500',
      'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=500',
      'https://images.unsplash.com/photo-1589998059171-988d887df646?w=500',
      'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500',
    ],
    priceRange: [10, 50],
    brands: [
      'Penguin',
      'Random House',
      'HarperCollins',
      'Simon & Schuster',
      'Macmillan',
      'Oxford',
      'Cambridge',
      'DK',
    ],
    description:
      'Engaging book that captivates readers with compelling stories and valuable insights.',
  },
  Sports: {
    count: 50,
    names: [
      'Professional Basketball',
      'Soccer Ball',
      'Tennis Racket',
      'Baseball Bat',
      'Golf Clubs Set',
      'Football',
      'Volleyball',
      'Badminton Racket',
      'Hockey Stick',
      'Cricket Bat',
      'Table Tennis Paddle',
      'Racquetball Racket',
      'Yoga Mat',
      'Dumbbells Set',
      'Resistance Bands',
      'Kettlebell',
      'Jump Rope',
      'Exercise Bike',
      'Treadmill',
      'Elliptical Machine',
      'Rowing Machine',
      'Weight Bench',
      'Pull-Up Bar',
      'Push-Up Handles',
      'Sports Watch',
      'Fitness Tracker',
      'Heart Rate Monitor',
      'Pedometer',
      'Running Shoes',
      'Training Shoes',
      'Cleats',
      'Sandals',
      'Sports Jersey',
      'Athletic Shorts',
      'Compression Shirt',
      'Sports Bra',
      'Swimsuit',
      'Goggles',
      'Swim Cap',
      'Water Bottle',
      'Sports Bag',
      'Gym Bag',
      'Backpack',
      'Duffel Bag',
      'Towel',
      'Sweatband',
      'Wristbands',
      'Headband',
      'Mouthguard',
      'Helmet',
      'Pads',
      'Protective Gear',
    ],
    colors: ['Black', 'White', 'Red', 'Blue', 'Green', 'Yellow'],
    images: [
      'https://images.unsplash.com/photo-1461896836934-561709ea56e3?w=500',
      'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=500',
      'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500',
      'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=500',
      'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=500',
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500',
      'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?w=500',
      'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=500',
    ],
    priceRange: [15, 500],
    brands: [
      'Nike',
      'Adidas',
      'Under Armour',
      'Puma',
      'Reebok',
      'Wilson',
      'Spalding',
      'Rawlings',
    ],
    description:
      'Professional sports equipment designed for performance and durability.',
  },
  Toys: {
    count: 50,
    names: [
      'LEGO Creative Set',
      'RC Car',
      'Board Game',
      'Art Supplies Kit',
      'Building Blocks',
      'Puzzle Set',
      'Doll House',
      'Action Figure',
      'Stuffed Animal',
      'Play Kitchen',
      'Tool Set',
      'Doctor Kit',
      'Science Kit',
      'Chemistry Set',
      'Telescope',
      'Microscope',
      'Robot Toy',
      'Drone for Kids',
      'Video Game Console',
      'Handheld Game',
      'Outdoor Playset',
      'Swing Set',
      'Slide',
      'Trampoline',
      'Bicycle',
      'Scooter',
      'Skateboard',
      'Roller Skates',
      'Play-Doh Set',
      'Modeling Clay',
      'Paint Set',
      'Drawing Tablet',
      'Musical Instrument',
      'Keyboard',
      'Drum Set',
      'Guitar',
      'Costume Set',
      'Dress-Up Clothes',
      'Puppet Theater',
      'Puppets',
      'Train Set',
      'Race Track',
      'Car Collection',
      'Dinosaur Set',
      'Space Toys',
      'Pirate Toys',
      'Castle Set',
      'Farm Set',
      'Animal Figures',
      'Play Food',
      'Cash Register',
      'Shopping Cart',
    ],
    colors: ['Red', 'Blue', 'Yellow', 'Green', 'Orange', 'Purple'],
    images: [
      'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=500',
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=500',
      'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=500',
      'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500',
      'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=500',
      'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=500',
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=500',
      'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=500',
    ],
    priceRange: [10, 200],
    brands: [
      'LEGO',
      'Hasbro',
      'Mattel',
      'Fisher-Price',
      'Play-Doh',
      'Crayola',
      'Nintendo',
      'Sony',
    ],
    description:
      'Fun and educational toy designed to inspire creativity and learning.',
  },
  Groceries: {
    count: 50,
    names: [
      'Organic Coffee Beans',
      'Extra Virgin Olive Oil',
      'Artisan Pasta Set',
      'Premium Tea Collection',
      'Organic Honey',
      'Whole Grain Bread',
      'Fresh Eggs',
      'Organic Milk',
      'Greek Yogurt',
      'Cheese Variety Pack',
      'Fresh Fruits Basket',
      'Vegetable Box',
      'Organic Salad Mix',
      'Avocados',
      'Berries Pack',
      'Lean Chicken Breast',
      'Ground Beef',
      'Salmon Fillet',
      'Shrimp',
      'Tuna Steak',
      'Brown Rice',
      'Quinoa',
      'Oats',
      'Granola',
      'Cereal',
      'Peanut Butter',
      'Almond Butter',
      'Jam Collection',
      'Honey',
      'Maple Syrup',
      'Olive Oil',
      'Coconut Oil',
      'Avocado Oil',
      'Vinegar Set',
      'Spices Collection',
      'Pasta Sauce',
      'Canned Tomatoes',
      'Beans Variety',
      'Lentils',
      'Chickpeas',
      'Snack Pack',
      'Nuts Mix',
      'Dried Fruits',
      'Energy Bars',
      'Protein Bars',
      'Chocolate Collection',
      'Cookies Pack',
      'Crackers',
      'Chips Variety',
      'Popcorn',
      'Soda Pack',
      'Juice Box',
      'Water Bottles',
      'Sports Drink',
      'Energy Drink',
      'Coffee Pods',
    ],
    colors: ['Brown', 'Green', 'Yellow', 'Red', 'White', 'Golden'],
    images: [
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500',
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500',
      'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=500',
      'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500',
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500',
      'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500',
      'https://images.unsplash.com/photo-1542838132-92c53300491e?w=500',
      'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=500',
    ],
    priceRange: [5, 100],
    brands: [
      'Starbucks',
      'Colavita',
      'De Cecco',
      'Twinings',
      "Nature Nate's",
      'Organic Valley',
      'General Mills',
      "Kellogg's",
    ],
    description:
      'Quality grocery item sourced from trusted suppliers for your daily needs.',
  },
};

// Helper function to generate products for a category
const generateProducts = (category, count, baseData) => {
  const products = [];
  for (let i = 0; i < count; i++) {
    const productName = baseData.names[i % baseData.names.length];
    const uniqueName = `${productName} - ${category} ${i + 1}`;
    const isOutOfStock = Math.random() < 0.15; // 15% chance of being out of stock
    // Add random parameter to image URL to ensure uniqueness
    const imageUrl = `${baseData.images[i % baseData.images.length]}&sig=${Math.floor(Math.random() * 1000000)}`;
    products.push({
      name: uniqueName,
      slug: `${productName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${category.toLowerCase()}-${i + 1}`,
      color: baseData.colors[i % baseData.colors.length],
      category: category,
      image: imageUrl,
      price:
        baseData.priceRange[0] +
        Math.random() * (baseData.priceRange[1] - baseData.priceRange[0]),
      countInStock: isOutOfStock ? 0 : Math.floor(Math.random() * 50) + 5,
      brand: baseData.brands[i % baseData.brands.length],
      rating: (Math.random() * 2 + 3).toFixed(1),
      numReviews: Math.floor(Math.random() * 500) + 50,
      description: `${productName} - ${baseData.description}`,
    });
  }
  return products;
};

// Generate all products
const products = [];
Object.keys(categoryData).forEach((category) => {
  const data = categoryData[category];
  const categoryProducts = generateProducts(category, data.count, data);
  products.push(...categoryProducts);
});

// Log sample slugs for debugging
console.log('\nSample product slugs:');
products.slice(0, 5).forEach((product) => {
  console.log(`${product.name} -> ${product.slug}`);
});

const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing products
    await Product.deleteMany({});
    console.log('Cleared existing products');

    // Insert new products
    await Product.insertMany(products);
    console.log('Products seeded successfully');

    // Verify a sample product exists
    const sampleProduct = await Product.findOne({
      slug: 'kindle-paperwhite-electronics-1',
    });
    if (sampleProduct) {
      console.log(
        'Sample product found:',
        sampleProduct.name,
        sampleProduct.slug,
      );
    } else {
      console.log('Sample product not found');
    }

    // Count products per category
    const categoryCounts = {};
    for (const category of Object.keys(categoryData)) {
      const count = await Product.countDocuments({ category });
      categoryCounts[category] = count;
    }

    console.log('\nCategory Product Counts:');
    Object.keys(categoryCounts).forEach((category) => {
      console.log(`${category}: ${categoryCounts[category]} products`);
    });

    console.log(`\nTotal products seeded: ${products.length}`);
    process.exit();
  } catch (error) {
    console.error('Error seeding products:', error);
    process.exit(1);
  }
};

seedProducts();
